openapi: 3.0.3

info:
  description: "Nomad Storage operations for peers"
  version: "1.0.0"
  title: Nomad API
  contact:
    email: iggydv12@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /yak-shop/load:
    post:
      summary: Load a new herd and reset the database
      operationId: loadHerd
      responses:
        '200':
          description: object stored successfully
        '400':
          description: invalid input, object invalid
        '500':
          description: server error
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Herd'
        description: game Object to add

components:
  schemas:
    LabYak:
      type: object
      required:
        - name
        - age
        - sex
      properties:
        name:
          type: string
          xml:
            name: 'name'
          minLength: 1
          example: Lilly
        age:
          description: Creation time in seconds (unix time)
          type: integer
          format: int64
          minimum: 1
          maximum: 10
          example: 5
        sex:
          description: Creation time in seconds (unix time)
          type: string
          maxLength: 1
          example: f
    Herd:
      type: object
      required:
        - herd
      properties:
        herd:
          type: array
          xml:
            name: 'herd'
          items:
            $ref: '#/components/schemas/LabYak'